### ISSUE TITLE
add to extra

### ISSUE THREAD

**Issue by omaru-ok** [metafates/scoop-mangal#1]
please add it to the  official extra [bucket](https://github.com/ScoopInstaller/Extras) 

[contribution guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md)

**Comment by omaru-ok** [comment]
one more thing if ur reading this 
i want some NSFW scraper in mangal 🥺

**Comment by metafates** [comment]
Hello, thanks for the suggestion!

I was thinking about adding it to the extra bucket but that would require me to make update pull-requests each time I update mangal (if I understood everything correctly). That's very annoying tbh + I'm too lazy to automate this process right now.

Speaking of NSFW - adding custom scrapers is always an option in the config file. I don't want to add NSFW sources by default

**Comment by omaru-ok** [comment]
ah oh okay :(
